[W 18:40:28.770 LabApp] All authentication is disabled.  Anyone who can connect to this server will be able to run code.
[I 18:40:30.738 LabApp] JupyterLab extension loaded from /home/de64/miniconda3/lib/python3.7/site-packages/jupyterlab
[I 18:40:30.738 LabApp] JupyterLab application directory is /home/de64/miniconda3/share/jupyter/lab
[I 18:40:30.741 LabApp] Serving notebooks from local directory: /home/de64/paulssonlab/paulssonlab/src/paulssonlab/deaton/trenchripper
[I 18:40:30.741 LabApp] The Jupyter Notebook is running at:
[I 18:40:30.741 LabApp] http://localhost:8888/
[I 18:40:30.741 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
slurmstepd: error: *** JOB 6711813 ON compute-f-17-09 CANCELLED AT 2020-04-30T18:40:37 ***
